### ISSUE TITLE
Step generator issue

### ISSUE THREAD

**Issue by Peterthegreat** [LamaBleu/moRFeus_GUI#1]
Hello

First of all, thanks for putting the time to build this tool. Great job

I am running with the following environment
```
Linux kali 4.12.0-kali2-amd64 #1 SMP Debian 4.12.13-1kali2 (2017-10-03) x86_64 GNU/Linux

yad version 0.38.2 (GTK+ 3.22.21)

bc version 1.07.1 (1.07.1-2+b1).

socat version 1.7.3.2 on Nov 19 2017 13:56:10 running on Linux version #1 SMP Debian 4.12.13-1kali2 (2017-10-03), release 4.12.0-kali2-amd64, machine x86_64

Going to download for 32 bits platform
--2018-08-03 08:39:30--  https://archive.othernet.is/morfeus_tool_v1.6/morfeus_tool_linux_x32
```

The program closes when pressing OK (with default settings) in the step generator window. No debugging info in the terminal.
Also, isn't Psynosaur/moRFeus_Qt supposed to be used over morfeus tool?

Thank you

**Comment by LamaBleu** [comment]
Hi @Peterthegreat , thank you for your feed back and trying.
When running the step generator, once you press OK ... Yes you are right, the task is running in background, and nothing is displayed during the step-process.
My plan was to implement a progress bar, but never did it, even if it's easy.
Just to be sure, try to launch a short sequence (let's say 10 steps, 1 second spaced), and you should go back to the main screen once it's done after 10 seconds.
And try to launch GUI_moRFeus from command line please ! Are you running in blind-mode or checking signal through RTL reveiver?
Regarding moRFeus_Qt from @Psynosaur it's another tool, written using Python, moreover multi-platform ;)  We did the tools at the same moment, sharing fun and info. FYI we are not affiliate to Outernet/Othernet.

**Comment by Peterthegreat** [comment]
Thanks for clearing that up. But once I pressed OK, the terminal from which I started the GUI is available again, indicating that the GUI has closed. That's why I am confused.
I am launching GUI_moRFeys from command line (is there another way? -running from linux-). The MoRFeus is connected to a spectrum analyzer (no clear CW signal there) as I am trying to measure 2.4GHz antennas for my first time. I will get back to you soon as the equipment is at my workplace.

I will also try with an RTL SDR

**Comment by LamaBleu** [comment]
Hi @Peterthegreat just tried to install moRFeus_GUI on a fresh linux install.
First, had problem to access the GUI. Using ./RPi_moRFeus.sh instead helped (modify morf_tool_path variable first) to finalize install.
Then back to GUI_moRFeus.sh I was able to run the main GUI (and test moRFeus and GQRX connection), and step generator.

Please find a log from the terminal :  

```
eric@EUROPA:~/moRFeus_GUI$ sudo ./GUI_moRFeus.sh 
Fstart: 179513000  Fend:  179713000  Step Hz: 10000 Hop-time: 1.0
 Jumps:  21   Power : 1   GQRX : No
*** Incremental steps !
Freq: 179513000 - GQRX: No - Jump 1/21   -  Level : none dB
Freq: 179523000 - GQRX: No - Jump 2/21   -  Level : none dB
Freq: 179533000 - GQRX: No - Jump 3/21   -  Level : none dB
Freq: 179543000 - GQRX: No - Jump 4/21   -  Level : none dB
Freq: 179553000 - GQRX: No - Jump 5/21   -  Level : none dB
Freq: 179563000 - GQRX: No - Jump 6/21   -  Level : none dB
Freq: 179573000 - GQRX: No - Jump 7/21   -  Level : none dB
Freq: 179583000 - GQRX: No - Jump 8/21   -  Level : none dB
Freq: 179593000 - GQRX: No - Jump 9/21   -  Level : none dB
Freq: 179603000 - GQRX: No - Jump 10/21   -  Level : none dB
Freq: 179613000 - GQRX: No - Jump 11/21   -  Level : none dB
Freq: 179623000 - GQRX: No - Jump 12/21   -  Level : none dB
Freq: 179633000 - GQRX: No - Jump 13/21   -  Level : none dB
Freq: 179643000 - GQRX: No - Jump 14/21   -  Level : none dB
Freq: 179653000 - GQRX: No - Jump 15/21   -  Level : none dB
Freq: 179663000 - GQRX: No - Jump 16/21   -  Level : none dB
Freq: 179673000 - GQRX: No - Jump 17/21   -  Level : none dB
Freq: 179683000 - GQRX: No - Jump 18/21   -  Level : none dB
Freq: 179693000 - GQRX: No - Jump 19/21   -  Level : none dB
Freq: 179703000 - GQRX: No - Jump 20/21   -  Level : none dB
Freq: 179713000 - GQRX: No - Jump 21/21   -  Level : none dB
Stepper end.    
gnuplot not installed
Normal exit
```
However I will take some time to double-check today and correct minor bug.
If you want to try again, just report the general behaviour, to narrow down the issue.
I suspect since a long time a problem will occur about numbers format and localization, not easy to manage from shell. But for me it's OK and tested on many platforms.
Regards.

Edit : corrected minor bug, tested on a fresh 64 bits platform - no problem here. just take care to download correct version 32 vs 64 bits.

Video - install process & step-generator : [http://www.lamableu.net/files/moRFeus_GUI-install.mkv](http://www.lamableu.net/files/moRFeus_GUI-install.mkv)

**Comment by LamaBleu** [comment]
Hi  @Peterthegreat

I finally added a progress bar (even two), allowing to check if all it's OK, and even stopping the step-generator during the process.
More over, there is a preview of signal plot during acquisition.
Please have a look to attached files. If you want to give a try, it is on the 'next' branch of this github repository (use : 'git checkout next' after 'git clone'). I will push it later to 'master' branch.
Regards.

![progressbar-1](https://user-images.githubusercontent.com/26578895/43831397-4be65008-9b04-11e8-94d3-1f21a51c7c01.png)
![progressbar-2](https://user-images.githubusercontent.com/26578895/43831399-4c08bc24-9b04-11e8-9645-d3fe60c4e310.png)

**Comment by Peterthegreat** [comment]
@LamaBleu Thanks for your effort in solving this, but the problem is still there. 
[https://streamable.com/mgibo](https://streamable.com/mgibo)

Am I doing something wrong?
I also tried with gqrx opened, even though my localhost is "::1"

EDIT: I found a hardcoded 32x OS in the script.

**Comment by Peterthegreat** [comment]
Tried from an archlinux and the behavior is the same. Other commands in the GUI seems to work

**Comment by LamaBleu** [comment]
Hi Peter,

Thanks for coming back. Your video is very useful and I'm sure you are close to find the solution :)
Few remarks after first viewing : 
- The script is unable to locate the install directory. Sometimes trying to access moRFeus_GUI or moRFeus_GUI next.
- you don't need to edit the file to choose 32/64 bits version. Just answer '32' or '64' . If you have issue at this step, please report.

Lot of suggestions, however trying to stay simple. From now I will speak only about the 'next' branch !
- try to extract the files to /root/moRFeus_GUI , not moRFeus_GUI-next
- try to launch the script using 'sudo -H ./GUI_morfeus' (or gksudo -H)
- you can also modify lines 43 and 46 in GUI_moRFeus.sh ($morf_tool_path $MORF_USER), to final path and username.

Once we can norrow-down the issue I'll try to correct it.

Regarding  GQRX, add in  remote control settings menu the IP 127.0.0.1 if connecting from localhost. 
The existing one by default is not enough.

You can test the connection to GQRX using 'nc' command : _nc 127.0.0.1 7356_ then send commands to GQRX to get signal level and freq : 

`user@EUROPA:~/moRFeus_GUI$ nc 127.0.0.1 7356  `
`f  `
`152426000  `
`l  `
`-73.6  `


I will take more time this evening, to better understand your issue. Perhaps add a full video. 
Will update here if needed.

Thanks and regards.

**Comment by LamaBleu** [comment]
Reviewing your video, I think I found your issue, confirming my previous update.

Please find attached a corrected GUI_moRFeus.sh file. Copy it to the directory, replacing original file.
Make it executable : chmod +x ./GUI_moRFeus.sh
Hope this will solve your issue.

I also found a possible problem on file permissiosn following transfer to github: to be confirmed, **and you are perhaps not concerned**.
Just in case if you get errors on permissions, the workaround is (from the moRFeus_GUI directory, use sudo if it's fail a simple user):
```
chmod 775 *.sh
chmod 644 *.gnu
chmod 755 .
chmod 755 datas
```


If patched file doesn't help, please try to apply workaround from my previous message.
Regards.
btw, from which country are you ? (answer is not mandatory to get support ;) )

[GUI_moRFeus.sh.zip](https://github.com/LamaBleu/moRFeus_GUI/files/2271290/GUI_moRFeus.sh.zip)

**Comment by Peterthegreat** [comment]
After some thought, I realized that it can't be a user access restriction as I am logged in as root. So, a few "echo's" later, I found the problem at [line 364 ](https://github.com/LamaBleu/moRFeus_GUI/blob/0ec794d80c8826bf498f1890a1d838ac11559e53/GUI_moRFeus.sh#L364)

`${stepper_hop::-5}` should be `${stepper_hop:-5}`

I will test the other lines with "::" characters for my enviorment -- GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
 
Thanks for your help! :+1: 
PS check your inbox

**Comment by LamaBleu** [comment]
Hi @Peterthegreat thank you so much. Hope you can draw nice plots now.
After reviewing your video, my guess was you were running as root from a liveCD.
I never work as 'root' (and 'test') user on systems except the very little ones like Pluto or OpenWRT. ;)
I'm very surprised you got a bug at this line because I tested on many systems/platforms, and it's OK. 
However browsing commits it looks I encountered problems with that syntax on other variables, but I can't remember. Fixed now on 'master' branch.
Thanks again for involving in troubleshooting. Will reply later to your email ;)
